[package]
name = "novastar-core"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "Rust library for interacting with Novastar LED Screen processors"
repository = "https://github.com/joele89/novastar-core"
readme = "README.md"

[dependencies]
serialport = "~4.7.0"
socket2 = "~0.5.8"
tokio = { version = "1.43.0", features = ["full"] }
chrono = "~0.4.39"
num_enum = "0.7.3"
strum = "0.27.1"
strum_macros = "0.27.1"
debug_print = "1.0.0"

[[test]]
name = "tests"
path = "src/tests.rs"
